"""fix_article_annotation_relation: create annotation table

Revision ID: 1173b4582d8e
Revises: b61dc0a4e61d
Create Date: 2025-09-19 14:45:18.264521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1173b4582d8e'
down_revision: Union[str, None] = 'b61dc0a4e61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sentences', 'annotation', ['annotation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentences', type_='foreignkey')
    # ### end Alembic commands ###
